SUNXI64_OVERLAYS = " \
        allwinner/overlay/sun50i-h5-analog-codec.dtbo \
        allwinner/overlay/sun50i-h5-cir.dtbo \
        allwinner/overlay/sun50i-h5-i2c0.dtbo \
        allwinner/overlay/sun50i-h5-i2c1.dtbo \
        allwinner/overlay/sun50i-h5-i2c2.dtbo \
        allwinner/overlay/sun50i-h5-pps-gpio.dtbo \
        allwinner/overlay/sun50i-h5-pwm.dtbo \
        allwinner/overlay/sun50i-h5-spdif-out.dtbo \
        allwinner/overlay/sun50i-h5-spi-add-cs1.dtbo \
        allwinner/overlay/sun50i-h5-spi-jedec-nor.dtbo \
        allwinner/overlay/sun50i-h5-spi-spidev.dtbo \
        allwinner/overlay/sun50i-h5-uart1.dtbo \
        allwinner/overlay/sun50i-h5-uart2.dtbo \
        allwinner/overlay/sun50i-h5-uart3.dtbo \
        allwinner/overlay/sun50i-h5-usbhost0.dtbo \
        allwinner/overlay/sun50i-h5-usbhost1.dtbo \
        allwinner/overlay/sun50i-h5-usbhost2.dtbo \
        allwinner/overlay/sun50i-h5-usbhost3.dtbo \
        allwinner/overlay/sun50i-h5-w1-gpio.dtbo \
"

SUNXI_OVERLAYS = " \
        sun8i-h3-analog-codec.dts \
        sun8i-h3-cir.dts \
        sun8i-h3-i2c0.dts \
        sun8i-h3-i2c1.dts \
        sun8i-h3-i2c2.dts \
        sun8i-h3-pps-gpio.dts \
        sun8i-h3-pwm.dts \
        sun8i-h3-spdif-out.dts \
        sun8i-h3-spi-add-cs1.dts \
        sun8i-h3-spi-jedec-nor.dts \
        sun8i-h3-spi-spidev.dts \
        sun8i-h3-uart1.dts \
        sun8i-h3-uart2.dts \
        sun8i-h3-uart3.dts \
        sun8i-h3-usbhost0.dts \
        sun8i-h3-usbhost1.dts \
        sun8i-h3-usbhost2.dts \
        sun8i-h3-usbhost3.dts \
        sun8i-h3-w1-gpio.dts \
"