#!/bin/bash

# Set the performance governor to all CPUs
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null
echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor 2>/dev/null
echo performance > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor 2>/dev/null
echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor 2>/dev/null
